### PR TITLE
Extended symbol module

### PR DESCRIPTION
**Pull request by perfahlen**
## Purpose

* The extended symbol module animates a new position for a symbol on a map when the symbol get's an updated position.

## Does this introduce a breaking change?

```
[ ] Yes
[ x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

```
Click on the map to move the symbol
```

## What to Check
Verify that the following are valid
* The symbol moves

### CODE REVIEW

**Comment by rbrundritt** [comment]
I've gone through and rewrote this to make it a bit more reusable. Here are the changes I made:

- Created an abstract class for creating shapes that can be animated instead of wrapping the Symbol laye. This extends from the Shape class. Created a AnimatedPoint class. This allows the class to be used with any layer that supports rendering point data; bubble, symbol, heat map.
- Moved from setInterval to requestAnimationFrame. This is a lot less error prone, and works much better when running multiple animations at the same time. It also reduces resources and pauses the animation calculations when the page isn't in view (i.e. user is on another tab).
- Using a single global animation loop for better performance as well. Able to animate a few thousands points at the same time. 
- Added support for geodesic and pixel accurate animations (curved vs straight pixel paths).
- If you set the coordinates in the middle of the animation, it handles it gracefully animates to the new coordinate from the current animated position. 
- The duration is set when setting the coordinate but defaults to 0 if not specified and simply jumps to the final coordinate. 
- A boolean can be specified when setting the coordinate which tells it if it should animate over a geodesic or straight pixel path.

Check out the samples:

https://azuremapscodesamples.azurewebsites.net/?sample=Animate%20a%20point

https://azuremapscodesamples.azurewebsites.net/?sample=Animate%20multiple%20points

https://azuremapscodesamples.azurewebsites.net/?sample=Shape%20animaiton%20module%20options

**Comment by perfahlen** [comment]
Cool, awesome improvements!

**Comment by rbrundritt** [comment]
I was thinking about expanding this to support additional animation types. Currently it is a linear animation, but it would be fairly easy to override this and support things like acceleration. Also being combining some of the other samples into this module so things like snake line and animating points along a path would all extend from the AnimatedShape class. Good foundation for a future feature in the SDK, or as an open module (looking into do this with a bunch of the modules and go beyond just having these in samples, but also having NPM packages).

**Comment by perfahlen** [comment]
I think it is a good idea to group the samples into reusable modules and publish them as NPM packages. It makes sense as a first step towards being part of the SDK. Popular modules might be part of the SDK. Animations gives life to the map and makes it more interesting. 

In an animation module, just be able to set a point blink or pulse would helpful. Plenty of use cases.

**Pull request merged**
