### PR TITLE
added sample for grid polygons, squares inside polygons

### PR DESCRIPTION
**Pull request by perfahlen**
and how to bind  drawing tool to HTML-element

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
enter squares side distance, draw a polygon with example AzureMapsCodeSamples/Drawing Tools Module/Grid Polygons.html, rectangles should be created inside the polygon

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by rbrundritt** [comment]
Noticed a few bugs. If the size is small, like 10 meters, there is a bunch of missing polygons. Also noticed that if the size is large and away from equator, the grid looks offset due to the "squaring" which is ignoring the Mercator projection (would need to calculate all four corners). Not sure what effect you are going for. If you want it to be accurate, then should calculate all four corners. If you want it too look pretty, consider using a polygon pattern: https://azuremapscodesamples.azurewebsites.net/index.html?sample=Polygon%20Fill%20Pattern

**Comment by rbrundritt** [comment]
Also throws an error if you draw across the anti-meridian (low priority issue).

I'll take a look at modifying the code to be accurate.

**Comment by rbrundritt** [comment]
Noticed that Turf has gridding functions already with mask support. Trying to get it to work but not perfect. Moving this sample to the experimental folder for now.

**Comment by rbrundritt** [comment]
Do you have a use case for this sample? trying to understand when this would be useful.

**Comment by rbrundritt** [comment]
Ok, managed to get it working decently now. Doesn't support anti-meridian but works well everywhere else for the most part. Now live here: https://azuremapscodesamples.azurewebsites.net/index.html?sample=Draw%20gridded%20polygon

Also live in the Azure Gov cloud mirror of this project: https://azuremapscodesamples.azurewebsites.us/

**Comment by perfahlen** [comment]
Thanks @rbrundritt , didn't realize Turf has a gridding function. The use case is some industries, like environmental and forest industry divide their areas into smaller areas or squares. Each square will have a status etc.

**Pull request merged**
